[server]
listen_addr = "0.0.0.0"
port = 8090

[node]
name = "Porta Server"
role = "edge"

[database]
path = "porta.db"

[p2p]
tcp_port = 9000
quic_port = 9001
mdns_enable = true
dht_enable = true
external_addrs = []

[logging]
level = "info"
format = "compact"
